# Generated by Django 4.1.10 on 2023-10-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table_extraction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tables",
            field=models.TextField(blank=True, null=True),
        ),
    ]
